import math

item_1 = 3
item_2 = 9
result_sum = item_1 + item_2
print('result_sum = ', result_sum, type(result_sum))
result_subtr = item_2 - item_1
print('result_subtr = ', result_subtr)
result_multi = item_1 * item_2
print('result_multi = ', result_multi)
result_exp = item_1 ** item_2
print('result = ', result_exp)
result_m_exp = math.pow(item_1, item_2)
print('result_m_exp = ', result_m_exp)
result_s_root = item_2 ** 0.5
print('result_s_root = ', result_s_root)
result_m_s_root = math.sqrt(item_2)
print('result_m_s_root = ', result_m_s_root)
result_mp_s_root = math.pow(item_2, 0.5)
print('result_mp_s_root = ', result_mp_s_root)
item_1 = 15
item_2 = 10
result_devision = item_1 / item_2
print('result_devision = ', result_devision)
result_m_floor = math.floor(result_devision)
print('result_m_floor = ', result_m_floor)
result_m_ceil = math.ceil(result_devision)
print('result_m_ceil = ', result_m_ceil)
result_int = round(result_devision)
print('result_int = ', result_int)
result_no_division_loss = item_1 // item_2
print('result_no_division_loss = ', result_no_division_loss)
result_devision_loss = item_1 % item_2
print('result_devision_loss =', result_devision_loss)
item_3 = 7
item_3 += 10
print('item_3 = ', item_3)
item_3 -= 5
print('item_3 = ', item_3)
item_3 *= 3
print('item_3 = ', item_3)
item_3 /= 2
print('item_3 = ', item_3)
item_3 **= 2
print('item_3 = ', item_3)
item_3 **= 0.5
print('item_3 = ', item_3)
item_3 %= 7
print('item_3 = ', item_3)
b_item_t = True
b_item_f = False
b_item_relult_sum = b_item_t + b_item_f
print('b_item_relult_sum = ', b_item_relult_sum, type(b_item_relult_sum))
b_item_relult_subtr = b_item_t - b_item_f
print('b_item_relult_subtr = ', b_item_relult_subtr, type(b_item_relult_subtr))
b_item_relult_multi = b_item_t * b_item_f
print('b_item_relult_multi = ', b_item_relult_multi, type(b_item_relult_multi))
#b_item_relult_division = b_item_t / b_item_f
#print('b_item_relult_division = ', b_item_relult_division, type(b_item_relult_division))
b_item_1_int = int(b_item_t)
print('b_item_1_int = ', b_item_1_int)
b_item_2_int = int(b_item_f)
print('b_item_2_int = ', b_item_2_int)
